---
name: WWW-Zooomr-Scraper
version: v0.3.0
author:
  - 'Flavio Poletti <flavio [at] polettix [dot] it>'
abstract: upload files to Zooomr via website interface
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Path::Class: 0
  Test::More: 0
  WWW::Mechanize: 0
  version: 0
configure_requires:
  Module::Build: 0.35
provides:
  WWW::Zooomr::Scraper:
    file: lib/WWW/Zooomr/Scraper.pm
    version: v0.3.0
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
